## E-Commerce Customer Segmentation

DATASET DETAILS:

- InvoiceNo: Invoice number. Nominal. A 6-digit integral number uniquely assigned to each transaction. If this code starts with the letter 'c', it indicates a cancellation.
- StockCode: Product (item) code. Nominal. A 5-digit integral number uniquely assigned to each distinct product.
- Description: Product (item) name. Nominal.
- Quantity: The quantities of each product (item) per transaction. Numeric.
- InvoiceDate: Invice date and time. Numeric. The day and time when a transaction was generated.
- UnitPrice: Unit price. Numeric. Product price per unit in sterling (Â£).
- CustomerID: Customer number. Nominal. A 5-digit integral number uniquely assigned to each customer.
- Country: Country name. Nominal. The name of the country where a customer resides.

In [2]:
import numpy as np
import pandas as pd

### Data Loading

In [3]:
df = pd.read_csv('online_retail_II.csv')
df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067366,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
1067367,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
1067368,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
1067369,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France
1067370,581587,POST,POSTAGE,1,2011-12-09 12:50:00,18.00,12680.0,France

In [4]:
df.dtypes

Invoice         object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
Price          float64
Customer ID    float64
Country         object
dtype: object

In [5]:
print(df.columns)

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB
None

In [7]:
# Customer ID 824364-dir.Deməli "Bəzi transaction-larda müştəri ID-si yoxdur?"

In [8]:
df['Customer ID'].isnull().sum()

np.int64(243007)

In [9]:
# "If this code starts with the letter 'c', it indicates a cancellation". Neçə məhsul cancel edilmişdir?

In [10]:
print(df['Invoice'].str.startswith('C').sum())

19494

In [11]:
# Quantity -də bəzi datalar 0 və mənfidir. Bunu araşdıraq :

In [12]:
df[df['Quantity'] <= 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
...,...,...,...,...,...,...,...,...
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
1067002,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

In [13]:
df[df['Price'] <= 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1062442,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
1063965,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.0,NaN,United Kingdom
1063966,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.0,NaN,United Kingdom
1064015,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom
1064386,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom

In [14]:
# Indi isə duplicated datanı arasdiraq
df.duplicated().sum()

np.int64(34335)

In [15]:
df[df.duplicated(keep=False)].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom

In [16]:
# Analiz üçün df_clean yaradaq

# CustomerID missing values
df_clean = df.dropna(subset=['Customer ID']).copy()

# Quantity > 0
df_clean = df_clean[df_clean['Quantity'] > 0]

# Price > 0
df_clean = df_clean[df_clean['Price'] > 0]

# Duplicated values
df_clean = df_clean.drop_duplicates().copy()

# Convert InvoiceDate
df_clean['InvoiceDate'] = pd.to_datetime(df_clean['InvoiceDate'])

In [17]:
# Əməliyyatların icra olunduğunu yoxlayaq(validatin) :

In [18]:
# 1. Datasetin ölçüsü
print("Dataset shape:", df_clean.shape)

# 2. CustomerID missing values
print("Missing CustomerID:", df_clean['Customer ID'].isna().sum())

# 3. Duplicate rows
print("Duplicates:", df_clean.duplicated().sum())

# 4. Invalid Quantity
print("Quantity <= 0:", (df_clean['Quantity'] <= 0).sum())

# 5. Invalid UnitPrice
print("UnitPrice <= 0:", (df_clean['Price'] <= 0).sum())

# 6. InvoiceDate dtype
print("InvoiceDate dtype:", df_clean['InvoiceDate'].dtype)

Dataset shape: (779425, 8)
Missing CustomerID: 0
Duplicates: 0
Quantity <= 0: 0
UnitPrice <= 0: 0
InvoiceDate dtype: datetime64[ns]

## RFM

In [19]:
df_clean.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='object')

### Recency

In [20]:
customer_last_purchase = df_clean.groupby('Customer ID')['InvoiceDate'].max()
customer_last_purchase.head()

Customer ID
12346.0   2011-01-18 10:01:00
12347.0   2011-12-07 15:52:00
12348.0   2011-09-25 13:13:00
12349.0   2011-11-21 09:51:00
12350.0   2011-02-02 16:01:00
Name: InvoiceDate, dtype: datetime64[ns]

In [21]:
last_date = df_clean['InvoiceDate'].max()
last_date

Timestamp('2011-12-09 12:50:00')

In [22]:
recency = (last_date - customer_last_purchase).dt.days
recency

Customer ID
12346.0    325
12347.0      1
12348.0     74
12349.0     18
12350.0    309
          ...
18283.0      3
18284.0    431
18285.0    660
18286.0    476
18287.0     42
Name: InvoiceDate, Length: 5878, dtype: int64

### Frequency

In [23]:
frequency= df_clean.groupby('Customer ID')['Invoice'].nunique()
frequency.head()

Customer ID
12346.0    12
12347.0     8
12348.0     5
12349.0     4
12350.0     1
Name: Invoice, dtype: int64

### Monetary

In [24]:
df_clean['TotalAmount']= df_clean['Quantity']*df_clean['Price']

In [25]:
monetary = df_clean.groupby('Customer ID')['TotalAmount'].sum()
monetary

Customer ID
12346.0    77556.46
12347.0     4921.53
12348.0     2019.40
12349.0     4428.69
12350.0      334.40
             ...
18283.0     2664.90
18284.0      461.68
18285.0      427.00
18286.0     1296.43
18287.0     4182.99
Name: TotalAmount, Length: 5878, dtype: float64

In [26]:
rfm = pd.concat([recency,frequency,monetary],axis=1)

In [27]:
rfm.columns = ['Recency','Frequency','Monetary']
rfm

             Recency  Frequency  Monetary
Customer ID
12346.0          325         12  77556.46
12347.0            1          8   4921.53
12348.0           74          5   2019.40
12349.0           18          4   4428.69
12350.0          309          1    334.40
...              ...        ...       ...
18283.0            3         22   2664.90
18284.0          431          1    461.68
18285.0          660          1    427.00
18286.0          476          2   1296.43
18287.0           42          7   4182.99

[5878 rows x 3 columns]

In [28]:
rfm['R_Score'] = pd.qcut(rfm['Recency'],5,labels=[5, 4, 3, 2, 1])

In [29]:
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'),5,labels=[1,2,3,4,5])

In [30]:
rfm['M_Score'] = pd.qcut(rfm['Monetary'],5,labels=[1,2,3,4,5])

In [31]:
rfm['RFM_Total'] = ( rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str) )

In [32]:
rfm['RFM_Score'] = ( rfm['R_Score'].astype(int) + rfm['F_Score'].astype(int) + rfm['M_Score'].astype(int) )

In [33]:
rfm["Customer_segment"] = np.where(rfm['RFM_Score'] >= 12, "Top Customers",
                          np.where(rfm['RFM_Score'] >= 9, "High Value Customer",
                          np.where(rfm['RFM_Score'] >= 6, "Medium Value Customer",
                          "Low Value Customers")))

In [34]:
rfm['Customer_segment'].value_counts()

Customer_segment
Top Customers            1724
High Value Customer      1436
Medium Value Customer    1410
Low Value Customers      1308
Name: count, dtype: int64

In [35]:
rfm.groupby('Customer_segment')[['Recency', 'Frequency', 'Monetary']].mean()

                          Recency  Frequency     Monetary
Customer_segment
High Value Customer    128.371866   4.291783  1486.299210
Low Value Customers    457.733180   1.138379   245.905093
Medium Value Customer  237.873759   2.080142   649.557732
Top Customers           34.276102  15.303944  8122.365626

In [55]:
rfm_export['Monetary'] = rfm_export['Monetary'].round(2)
rfm_export = rfm.reset_index()
rfm_export.to_excel('rfm_customer_segments.xlsx', index=False)

In [57]:
rfm_export

,Customer ID,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Total,RFM_Score,Customer_segment
0,12346.0,325,12,77556.46,2,5,5,255,12,Top Customers
1,12347.0,1,8,4921.53,5,4,5,545,14,Top Customers
2,12348.0,74,5,2019.40,3,4,4,344,11,High Value Customer
3,12349.0,18,4,4428.69,5,3,5,535,13,Top Customers
4,12350.0,309,1,334.40,2,1,2,212,5,Low Value Customers
...,...,...,...,...,...,...,...,...,...,...
5873,18283.0,3,22,2664.90,5,5,4,554,14,Top Customers
5874,18284.0,431,1,461.68,1,2,2,122,5,Low Value Customers
5875,18285.0,660,1,427.00,1,2,2,122,5,Low Value Customers
5876,18286.0,476,2,1296.43,1,3,4,134,8,Medium Value Customer
5877,18287.0,42,7,4182.99,4,4,5,445,13,Top Customers